# ECE2112 - PA2


## A. Reproducible Normalization Problem

In [36]:
import numpy as np

In [37]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))

In [38]:
print (X)

[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]


In [39]:
mean = float (X.mean())
print ("Mean: ", mean)

Mean:  46.36


In [40]:
std = float (X.std())
print ("Standard Deviation: ", std)

Standard Deviation:  25.864075471588002


In [41]:
X_normalized = (X - X.mean() ) / X.std()

In [42]:
print (X_normalized)

[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]


In [43]:
print ("Normalized Mean: ", X_normalized.mean())

Normalized Mean:  0.0


In [44]:
print ("Normalized Standard Deviation: ", X_normalized.std())

Normalized Standard Deviation:  0.9999999999999999


In [45]:
np.save("X_normalized.npy", X_normalized)

## B. Cubes Divisible by 4 Problems

In [46]:
import numpy as np

In [47]:
integers = np.arange (1,101)
integers

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [48]:
cubes = integers ** 3
C = cubes.reshape (10, 10)
print ("Shape of C:", C.shape)

Shape of C: (10, 10)


In [49]:
div_by_4 = C[C % 4 == 0]

print ("Selected array div by 4:\n", div_by_4)

Selected array div by 4:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]


In [50]:
np.save("div_by_4.npy",div_by_4)

## C. Above-Mean Squares Problem

In [51]:
import numpy as np

In [52]:
S = (np.arange(1,37) ** 2).reshape(6,6)
print (S)

[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]


In [53]:
S_mean = float (S.mean())
print ("S_mean:", S_mean)

S_mean: 450.1666666666667


In [54]:
above_mean = S[S > S_mean]
print ("Above mean:", above_mean)

Above mean: [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]


In [55]:
print ("Number of selected elements:", len(above_mean))

Number of selected elements: 15


In [56]:
np.save("above_mean.npy", above_mean)